In [2]:
#NUMPY

In [71]:
import numpy as np

In [72]:
a=[]

In [73]:
for i in range(100):
    a.append(i)
    

In [74]:
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [75]:
type(a)

list

In [76]:
# we need to work with arrays, jitni bhi calculation hoti hai woh arrays pe hoti hai 

In [77]:
a=np.array(a)

In [86]:
a[:50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [173]:
b=np.array([[1,2,3,4,5],[2,3,4,5,6]])

In [37]:
b

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [40]:
b[1][2]

4

In [41]:
type(b)

numpy.ndarray

In [42]:
b.shape

(2, 5)

In [54]:
# len(b[0])

# a=[[1,2,3,4,5],[1,2,3,4,5]]

# b=a[0]

# b

# b[1]

# a[0][1]



In [59]:
c=np.full((3,2),5)

In [60]:
c

array([[5, 5],
       [5, 5],
       [5, 5]])

In [61]:
#identity matrix diagonals are 1 and rest of the elments are 0

In [66]:
np.eye(4,2,dtype=int)

array([[1, 0],
       [0, 1],
       [0, 0],
       [0, 0]])

In [98]:
randoms=np.random.random((5,6))

In [99]:
randoms

array([[0.17945139, 0.28303951, 0.09239602, 0.35216731, 0.98619542,
        0.0547478 ],
       [0.26657199, 0.35768874, 0.47984899, 0.58754765, 0.59403249,
        0.07700294],
       [0.88952045, 0.19287099, 0.43948848, 0.03064514, 0.59767335,
        0.48246639],
       [0.90396571, 0.41993716, 0.12745285, 0.07766246, 0.81210975,
        0.85885153],
       [0.05175172, 0.28032072, 0.68422463, 0.84175433, 0.9094859 ,
        0.56203092]])

In [100]:
# randoms=randoms[0]

In [102]:
randoms[3:,:2]  #, daalke is for 2d array, not for singular array 

array([[0.90396571, 0.41993716],
       [0.05175172, 0.28032072]])

In [104]:
# randoms[3:]

In [105]:
X=np.array([[1,2],[3,4]])
Y=np.array([[5,6],[7,8]])

In [107]:
X.shape,Y.shape

((2, 2), (2, 2))

In [108]:
X+Y

array([[ 6,  8],
       [10, 12]])

In [109]:
np.add(X,Y)

array([[ 6,  8],
       [10, 12]])

In [110]:
np.subtract(X,Y)

array([[-4, -4],
       [-4, -4]])

In [111]:
X-Y

array([[-4, -4],
       [-4, -4]])

In [112]:
np.multiply(X,Y)

array([[ 5, 12],
       [21, 32]])

In [113]:
X*Y

array([[ 5, 12],
       [21, 32]])

In [114]:
np.matmul(X,Y)

array([[19, 22],
       [43, 50]])

In [115]:
X@Y

array([[19, 22],
       [43, 50]])

In [116]:
np.divide(X,Y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [117]:
X/Y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [118]:
np.sqrt(X)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [120]:
np.dot(X,Y)

array([[19, 22],
       [43, 50]])

In [121]:
X.dot(Y)

array([[19, 22],
       [43, 50]])

In [122]:
arr=np.array([[1,2,3],[4,5,6]])  #100

In [125]:
flattened=arr.flatten()   #105

In [130]:
flattened              #creates and return a copy in memory 

array([1, 2, 3, 4, 5, 6])

In [128]:
ravel= arr.ravel()    #100

In [131]:
ravel                 # changes affect the orignal array 

array([1, 2, 3, 4, 5, 6])

In [132]:
# stack
# randint
# ones , zeros
# min max mean
# average
# std

In [133]:
a=np.array([1,2,3,4,5])
b=np.array([1,2,3,4,5])


In [134]:
b=b**2

In [135]:
b

array([ 1,  4,  9, 16, 25])

In [136]:
np.stack((a,b),axis=0),np.stack((a,b),axis=0).shape

(array([[ 1,  2,  3,  4,  5],
        [ 1,  4,  9, 16, 25]]),
 (2, 5))

In [137]:
np.stack((a,b),axis=1),np.stack((a,b),axis=1).shape

(array([[ 1,  1],
        [ 2,  4],
        [ 3,  9],
        [ 4, 16],
        [ 5, 25]]),
 (5, 2))

In [140]:
a=np.stack((a,b),axis=0)

In [141]:
a

array([[ 1,  2,  3,  4,  5],
       [ 1,  4,  9, 16, 25]])

In [142]:
a.shape

(2, 5)

In [145]:
a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  1],
       [ 4,  9],
       [16, 25]])

In [149]:
x=np.random.randint(10,50,15)  #random integer, 10 is lower limit , 20 is upper limit, 3 is the number of elements

In [150]:
x

array([43, 47, 41, 33, 16, 31, 28, 15, 36, 14, 30, 20, 37, 19, 16])

In [151]:
choice= np.random.choice(x)

In [152]:
choice

28

In [154]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [158]:
np.ones((5,6),dtype=int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [159]:
a

array([[ 1,  2,  3,  4,  5],
       [ 1,  4,  9, 16, 25]])

In [162]:
a=a.flatten()

In [166]:
x

array([43, 47, 41, 33, 16, 31, 28, 15, 36, 14, 30, 20, 37, 19, 16])

In [165]:
np.min(x)

14

In [167]:
np.max(x)

47

In [168]:
np.average(x)

28.4

In [170]:
np.mean(x)

28.4

In [171]:
np.std(x)

10.750503864160661

In [174]:
b

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [175]:
np.expand_dims(b,axis=0)

array([[[1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6]]])

In [176]:
np.expand_dims(b,axis=1)

array([[[1, 2, 3, 4, 5]],

       [[2, 3, 4, 5, 6]]])